apiVersion: wgpolicyk8s.io/v1alpha2
kind: ClusterPolicyReport
metadata:
  creationTimestamp: "2022-08-22T18:15:30Z"
  generation: 2
  labels:
    app.kubernetes.io/created-by: trivy-operator-polr-adapter
    trivy-operator.source: ClusterRbacAssessmentReport
  name: trivy-rbac-cpolr-clusterrole-5585c7b9ff
  ownerReferences:
  - apiVersion: rbac.authorization.k8s.io/v1
    blockOwnerDeletion: false
    controller: true
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  resourceVersion: "39436"
  uid: 2296a252-b108-4d4a-b705-4b8983babe2b
results:
- category: Kubernetes Security Check
  message: Some workloads leverage configmaps to store sensitive data or configuration
    parameters that affect runtime behavior that can be modified by an attacker or
    combined with another issue to potentially lead to compromise.
  policy: Do not allow management of configmaps
  properties:
    resultID: d06e66683ee5de1136d5996ae0f4e1ae9b5d85c7
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV049
  severity: medium
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits privilege escalation from node proxy
  policy: Do not allow privilege escalation from node proxy
  properties:
    resultID: 519454bf1ec35b55d0d8041fb191017bf83519d3
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV047
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits managing secrets
  policy: Do not allow management of secrets
  properties:
    resultID: 58ce9ae48cbb7a174bf369762aa5b12cb9ee7979
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV041
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits creating role ClusterRoleBindings and association
    with privileged cluster role
  policy: Do not allow role to create ClusterRoleBindings and association with privileged
    role
  properties:
    resultID: c2d65757bda07a192ac790ea2616446e29c96e01
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV052
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits specific verb on wildcard resources
  policy: No wildcard resource roles
  properties:
    resultID: 331b61aa44d11e7446fbd19b6be1491dd153fa10
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV046
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Used to cover attacker’s tracks, but most clusters ship logs quickly off-cluster.
  policy: Do not allow deletion of pod logs
  properties:
    resultID: ca7c9a8000d3051e06da59e0d9d2d9cd94cb96f5
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV042
  severity: medium
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits attaching to shell on pods
  policy: Do not allow attaching to shell on pods
  properties:
    resultID: 6646b4543b237419d79947b6cc302c05873c9ca5
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV054
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: An effective level of access equivalent to cluster-admin should not be
    provided.
  policy: Do not allow management of RBAC resources
  properties:
    resultID: 8685d60f517bab32f5612175e27bb71b930df960
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV050
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits update/create of a malicious pod
  policy: Do not allow update/create of a malicious pod
  properties:
    resultID: c725e2d9d50eb504816107a63baea6ed03c326a8
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV048
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits wildcard verb on specific resources
  policy: No wildcard verb roles
  properties:
    resultID: d579ba007c97103ed994b01c888ba9860e0595fe
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV045
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits wildcard verb on wildcard resource
  policy: No wildcard verb and resource roles
  properties:
    resultID: 630983e8ae00da731e39fe44d7934514ae2b0b60
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV044
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits getting shell on pods
  policy: Do not allow getting shell on pods
  properties:
    resultID: 450e0a16561c693995ceb5b6cc598e89d0525480
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV053
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: The ability to control which pods get service traffic directed to them
    allows for interception attacks. Controlling network policy allows for bypassing
    lateral movement restrictions.
  policy: Do not allow management of networking resources
  properties:
    resultID: d686ab3dfa19c6933a5cc2db806124f717596374
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV056
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits creating role bindings and associating to privileged
    role/clusterrole
  policy: Do not allow role binding creation and association with privileged role/clusterrole
  properties:
    resultID: 1a8863b87f14f32438e7a91fd2b72b5152b8bc0a
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV051
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits allowing users in a rolebinding to add other
    users to their rolebindings
  policy: Do not allow users in a rolebinding to add other users to their rolebindings
  properties:
    resultID: 601c22378f3634d55b52f300c7282ccc253deb06
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV055
  severity: low
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
- category: Kubernetes Security Check
  message: Check whether role permits impersonating privileged groups
  policy: Do not allow impersonation of privileged groups
  properties:
    resultID: b278434576278038ae52d422924c0ccdad57ccbd
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: system:certificates.k8s.io:kubelet-serving-approver
    uid: 21449ac8-2f58-4eff-8f3d-c9e4e0024821
  result: pass
  rule: KSV043
  severity: high
  source: Trivy RbacAssessment
  timestamp:
    nanos: 0
    seconds: 1661165899
summary:
  error: 0
  fail: 0
  pass: 16
  skip: 0
  warn: 0
